chore: removed step 'Validate project structure'

diff --git a/.github/workflows/build-deploy-flutter.yaml b/.github/workflows/build-deploy-flutter.yaml
--- a/.github/workflows/build-deploy-flutter.yaml
+++ b/.github/workflows/build-deploy-flutter.yaml
@@ -28,17 +28,17 @@ jobs:
           cd ${{ github.workspace }}/project
           flutter pub get
 
-      - name: Validate project structure
-        run: |
-          cd ${{ github.workspace }}/project
+      # - name: Validate project structure
+      #   run: |
+      #     cd ${{ github.workspace }}/project
           
-          if ! [[ -d "android" && -d "ios" && -d "android/app" && -d "ios/Runner" && -f "pubspec.yaml" ]]; then
-            echo "Project structure is not supported by Flutter or missing required files/directories."
-            echo "Creating a new Flutter project..."
-            mv pubspec.yaml pubspec.temp.yaml
-            flutter create .
-            mv pubspec.temp.yaml pubspec.yaml
-          fi
+      #     if ! [[ -f "pubspec.yaml" ]]; then
+      #       echo "Project structure is not supported by Flutter or missing required files/directories."
+      #       echo "Creating a new Flutter project..."
+      #       mv pubspec.yaml pubspec.temp.yaml
+      #       flutter create .
+      #       mv pubspec.temp.yaml pubspec.yaml
+      #     fi
 
       - name: Move code and assets to new project
         run: |
